map_location_from_endpoints: 
  description: >
    Your task is to abide by the following mapping instructions:
      1. For each location endpoint in the following list: {location_endpoints}, create a new location object: 
        a. Use the GetForecastZoneTool to retrieve geographic related information about the event.
        b. Use the list of coordinatess from the GetForecastZoneTool response to set the `Location.shape` field. DO NOT TRUNCATE THE LIST OF COORDINATES. ENSURE THE ENTIRE LIST IS INCLUDED. 
        c. `Location.event_key` should use the following value: {event_key} 
        d. `Location.episode_key` can be set to None.
        e. `Location.ugc_code` should use the UGC code from the GetForecastZoneTool response.
        e. Use your knowledge about the event's geographical location to set a `Location.state_fips` code. 
        f. Use your knowledge about the event's geographical location to set a `Location.county_fips` code.
  expected_output: >
    A Locations object.
    E.g., 
    {
      "locations": [
      {
          "event_key": "ABC-123",
          "episode_key": None,
          "ugc_code": "SOME_CODE",
          "state_fips": 06,
          "county_fips": 06037,
          "shape": [{"latitude": 0.0, "longitude": 0.0}, {"latitude": 1.0, "longitude": 1.0}]
        }
      ]
    }
    }

map_event_type:
  description: >
    For this task, you must abide by the following mapping instructions:
      1. Recognize the abbreviated event type here: {abbreviated_event_type} .
      2. Use your knowledge about the NWS VTEC codes to map the abbreviated event type to a human-readable event name.
        E.g., "TOR" -> "TORNADO WARNING", "WSW" -> "WINTER STORM WARNING"  
  expected_output: >
    A HumanReadableEvent object. 
    E.g., 
    {
      "event_name": "TORNADO WARNING"
      "event_code": "TOR"
    }

construct_event_model: 
  description: >
    For this task, you must abide by the following mapping instructions:
      1. First, ensure you have a Locations object from the previous task.
      2. Second, ensure you have a HumanReadableEvent object from the previous task.
      3. `Event.event_key` should use the following value: {event_key}
      4. `Event.nws_alert_id` should use the following value: {nws_alert_id}
      5. `Event.hr_event_type` should use the HumanReadableEvent.event_name value.
      6. `Event.event_type` should use the HumanReadableEvent.event_code value.
      7. `Event.locations` should use the list of `Location` objects from the previous task.
      8. `Event.start_date` should use the following value: {start_date}
      9. `Event.description` should use the following value: {description}
      10. `Event.is_active` should be set to True.
      11. All remaining fields should be set to None.
  expected_output: >
    A ConstructedEventModel object.
    E.g., 
      {
        "event": {
          "event_key": "ABC-123",
          "nws_alert_id": "NWS-123",
          "hr_event_type": "TORNADO WARNING",
          "event_type": "TOR",
          "locations": [{"ugc_code": "SOME_CODE", "shape": [{"latitude": 0.0, "longitude": 0.0}, {"latitude": 1.0, "longitude": 1.0}]}],
          "start_date": "2021-01-01T00:00:00Z",
          "description": "A tornado warning has been issued for the area.",
          "is_active": True
        }
      }
    }

ensure_event_model_is_sound:
  description: >
    Your task is to provide a final, verified, definitive event model; data quality and accuracy are important.
    To accomplish this task, review the `ConstructedEventModel` object from the previous task. 
    You must check your findings. Ensure no hallucinations occurred or incorrect information. If there is incomplete information, you must correct it.
    Lastly, once the event model is verified, use the `VerifiedEventModel` and return it. 
    Once completed, this will signify the end of the agentic process between all agents.
  expected_output: >  
    A VerifiedEventModel object.
    E.g., 
    {
      "event": {
        "event_key": "ABC-123",
        "nws_alert_id": "NWS-123",
        "hr_event_type": "TORNADO WARNING",
        "event_type": "TOR",
        "locations": [{"ugc_code": "SOME_CODE", "shape": [{"latitude": 0.0, "longitude": 0.0}, {"latitude": 1.0, "longitude": 1.0}]}],
        "start_date": "2021-01-01T00:00:00Z",
        "description": "A tornado warning has been issued for the area.",
        "is_active": True
      }
    }